[package]
name = "counter-world"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd = { workspace = true }
gmeta = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
temple-types = { workspace = true }
